version: '3'

x-php-defaults: &php-defaults
  depends_on:
     postgres :
       condition: service_healthy
  build: ./php
  volumes:
    - ~/.composer-docker/cache:/root/.composer/cache:delegated
    - ../:/app:delegated
  env_file:
    - ../.env
  environment:
    - POSTGRES_DB_NAME=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_HOST=postgres

services:

  php:
    <<: *php-defaults
    container_name: image-supervisor-php
    build: ./php
    ports:
      - '80:80'
    restart: always
    depends_on:
      - php-migrations
      - php-composer

  # php container for migrations
  php-migrations:
    <<: *php-defaults
    container_name: image-supervisor-php-migrations
    command: ['php', 'yii', 'migrate/up']
    restart: on-failure
    depends_on:
      - php-composer

  php-composer:
    <<: *php-defaults
    container_name: image-supervisor-php-composer
    command: ['composer', 'install']
    restart: on-failure

  postgres:
    image: postgres:alpine
    container_name: image-supervisor-postgres
    volumes:
      - db:/var/lib/postgresql/data
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - POSTGRES_DB_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db: